name: sound_library
description: Easy UI sounds to directly use in your app through mis develop sound library database
version: 0.1.1
homepage: https://github.com/SirLegui/sound_library

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  storage_manager: ^0.1.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
